'use strict';

const { FULFILLMENT_MODES, SUPPORT_LEVELS } = require('../providerProduct.model');

const FAZERCARDS_FAMILIES = Object.freeze({
    TOPUPS: Object.freeze({
        familyKey: 'TOPUPS',
        displayName: 'Top-ups',
        itemType: 'topup_offer',
        catalogEndpoints: ['GET /topups', 'GET /topups/offers'],
        suggestedFulfillmentMode: FULFILLMENT_MODES.TOPUP_WITH_FIELDS,
        supportLevel: SUPPORT_LEVELS.FULL_TOPUP_SUPPORTED,
        status: 'implemented',
        catalogAvailable: true,
        executionAvailable: true,
        executionEnabled: false,
        executionGloballyGated: true,
    }),
    GIFTCARDS: Object.freeze({
        familyKey: 'GIFTCARDS',
        displayName: 'Gift Cards',
        itemType: 'gift_card',
        catalogEndpoints: ['GET /giftcards', 'GET /giftcards/cards'],
        suggestedFulfillmentMode: FULFILLMENT_MODES.CODE_DELIVERY,
        supportLevel: SUPPORT_LEVELS.NEEDS_CODE_DELIVERY,
        status: 'catalog_only',
        catalogAvailable: true,
        executionAvailable: false,
        executionEnabled: false,
        blockReason: 'CODE_DELIVERY_NOT_IMPLEMENTED',
        warning: 'Code delivery is not implemented yet.',
    }),
    GAME_KEYS: Object.freeze({
        familyKey: 'GAME_KEYS',
        displayName: 'Game Keys',
        itemType: 'game_key',
        catalogEndpoints: ['GET /gamekeys', 'GET /gamekeys/keys'],
        optionalCatalogEndpoints: ['GET /gamekeys/region-restriction'],
        suggestedFulfillmentMode: FULFILLMENT_MODES.CODE_DELIVERY,
        supportLevel: SUPPORT_LEVELS.NEEDS_CODE_DELIVERY,
        status: 'catalog_only',
        catalogAvailable: true,
        executionAvailable: false,
        executionEnabled: false,
        blockReason: 'CODE_DELIVERY_NOT_IMPLEMENTED',
        warning: 'Game key code delivery is not implemented yet.',
    }),
    STEAM_TOPUP: Object.freeze({
        familyKey: 'STEAM_TOPUP',
        displayName: 'Steam Wallet Top-up',
        itemType: 'steam_topup_rate',
        catalogEndpoints: ['GET /steam-topup/rates'],
        suggestedFulfillmentMode: FULFILLMENT_MODES.STEAM_TOPUP_WITH_LOGIN,
        supportLevel: SUPPORT_LEVELS.NEEDS_SPECIAL_FIELDS,
        status: 'catalog_only',
        catalogAvailable: true,
        executionAvailable: false,
        executionEnabled: false,
        blockReason: 'STEAM_TOPUP_EXECUTION_NOT_IMPLEMENTED',
        warning: 'Steam top-up execution is not implemented yet.',
    }),
    STEAM_GIFTS: Object.freeze({
        familyKey: 'STEAM_GIFTS',
        displayName: 'Steam Gifts',
        itemType: 'steam_gift',
        catalogEndpoints: ['GET /steam-gifts/games', 'GET /steam-gifts/games/:appid'],
        suggestedFulfillmentMode: FULFILLMENT_MODES.STEAM_GIFT_INVITE,
        supportLevel: SUPPORT_LEVELS.NEEDS_SPECIAL_FIELDS,
        status: 'catalog_only',
        catalogAvailable: true,
        executionAvailable: false,
        executionEnabled: false,
        blockReason: 'STEAM_GIFT_EXECUTION_NOT_IMPLEMENTED',
        warning: 'Steam gift invite execution is not implemented yet.',
    }),
    TELEGRAM: Object.freeze({
        familyKey: 'TELEGRAM',
        displayName: 'Telegram',
        itemType: 'telegram_digital_good',
        catalogEndpoints: ['GET /telegram/stars', 'GET /telegram/premium'],
        suggestedFulfillmentMode: FULFILLMENT_MODES.TELEGRAM_STARS_TOPUP,
        supportLevel: SUPPORT_LEVELS.NEEDS_SPECIAL_FIELDS,
        status: 'catalog_only',
        catalogAvailable: true,
        executionAvailable: false,
        executionEnabled: false,
        blockReason: 'TELEGRAM_EXECUTION_NOT_IMPLEMENTED',
        warning: 'Telegram Stars/Premium execution is not implemented yet.',
    }),
    MANUAL_SERVICES: Object.freeze({
        familyKey: 'MANUAL_SERVICES',
        displayName: 'Manual Services',
        itemType: 'manual_service_offer',
        catalogEndpoints: ['GET /manual-services', 'GET /manual-services/:manualServiceId/offers'],
        suggestedFulfillmentMode: FULFILLMENT_MODES.MANUAL_SERVICE,
        supportLevel: SUPPORT_LEVELS.NEEDS_SPECIAL_FIELDS,
        status: 'catalog_only',
        catalogAvailable: true,
        executionAvailable: false,
        executionEnabled: false,
        blockReason: 'MANUAL_SERVICE_EXECUTION_NOT_IMPLEMENTED',
        warning: 'Manual service execution/chat workflow is not implemented yet.',
    }),
    UNKNOWN: Object.freeze({
        familyKey: 'UNKNOWN',
        displayName: 'Unknown',
        itemType: 'unknown',
        catalogEndpoints: [],
        suggestedFulfillmentMode: FULFILLMENT_MODES.UNKNOWN,
        supportLevel: SUPPORT_LEVELS.DISCOVERY_UNCONFIRMED,
        status: 'discovery_unconfirmed',
        catalogAvailable: false,
        executionAvailable: false,
        executionEnabled: false,
        blockReason: 'DISCOVERY_UNCONFIRMED',
        warning: 'FazerCards family endpoint is not confirmed.',
    }),
});

const getFazerCardsFamily = (familyKey) => FAZERCARDS_FAMILIES[String(familyKey || '').trim().toUpperCase()] || null;

const listFazerCardsFamilies = () => Object.values(FAZERCARDS_FAMILIES);

module.exports = {
    FAZERCARDS_FAMILIES,
    getFazerCardsFamily,
    listFazerCardsFamilies,
};
